### ISSUE TITLE
MapperListOf not working properly

### ISSUE THREAD

**Issue by jadeade** [danieleteti/delphimvcframework#132]
Hi All

I am facing an issue when I am sending a list of objects and getting a list of different objects as an answer

Having this declaration:

    [RESTResource(httpPOST, PATH_TO_RESOURCE)]
    [MapperListOf(TReturnObject)]
    function APostFunction([Body] const ABody: TList<TSentObject>): TList<TReturnObject>;

Seems that the MapperListOf(TReturnObject) is also being applied to the ABody Param and it doesn't work. I tried also using MapperListOf(TSentObject) and then the problem comes with the result (the answer data from the WS)

I also tried to introduce a MapperListOf(TSentObject) attribute applied to the ABody param (inside the signature of the function) and leaving the MapperListOf(TReturnObject) mapper for the answer as attribute of the function and did not work

As far as I understand, the mapper should not be necessary for the ABody, as the framework should infer the correct types using RTTI, and the MapperListOf attribute should only be applied to the answer data. Seems that once the MapperListOf is defined, it's used for every list, no matter it's in the signature of the function or the function result itself. Am I correct? Is this a bug or is it expected to be working this way?

Thanks in advance

**Comment by BimmerR** [comment]
If I understand you correct. You try to use MapperListOf in your controller?
First - use MVCListOfAttribute since MapperListOf is marked deprecated.
Second - use in your class, not in the controller.

Look here [https://danieleteti.gitbooks.io/delphimvcframework/content/chapterrenders.html](url)
In the section about "Rendering objects and list of objects" 

    [MapperListOf(TNested)]
    property NestedList: TObjectList<TNested> read FNestedList write SetNestedList;

This way there should be no problems in sending in one list type and getting another type back.
