### ISSUE TITLE
replace indy to IOCP framework?

### ISSUE THREAD

**Issue by peihexian** [danieleteti/delphimvcframework#136]
indy framework have a lot of bug! 
can u replace indy to  iocp framework? such as  https://github.com/ymofen/diocp-v5 ?

**Comment by danieleteti** [comment]
It is in the wish list since 8 years (the very first version of dmvc, whe it was a private [bittimeprofessionals](http://www.bittimeprofessionals.com) project, used that project to access IOCP. However all the comments/documentation/sampels are only in chinese and that discouraged the inclusion in the official version.
