### ISSUE TITLE
delphi 10 Seattle error

### ISSUE THREAD

**Issue by krivoj** [danieleteti/delphimvcframework#196]
error #1:
          // Set very short timeouts: this is a local call and we don't want to block the queue for too long.
          lHTTPCli.ConnectionTimeout := 100;
          lHTTPCli.ResponseTimeout := 200;
undeclarated indentifier (ConnectionTimeout  and ResponseTimeout )

error #2:
    class function GetByPK<T: TMVCActiveRecord, constructor>(const aValue: int64): T; overload;
[dcc32 Error] MVCFramework.ActiveRecord.pas(218): E2086 Type 'TMVCActiveRecord' is not yet completely defined

**Comment by danieleteti** [comment]
The first error has been fixed in the repo, the second one is a bit tricky to fix without a working environment with Seattle. Can you do some tests and find what is the problem?

**Comment by krivoj** [comment]
i try.

**Comment by krivoj** [comment]
same error on Delphi Berlin

**Comment by davuteryilmaz** [comment]
I did a search on the problem and seems it's a bug fixed in Tokyo. Please check [https://stackoverflow.com/questions/34610900/using-own-class-as-a-type-parameter-constraint-in-class-declaration](https://stackoverflow.com/questions/34610900/using-own-class-as-a-type-parameter-constraint-in-class-declaration) and [https://quality.embarcadero.com/browse/RSP-13348](https://quality.embarcadero.com/browse/RSP-13348). Using class helpers or abstract base class is suggested as a workaround.

**Comment by oakrom** [comment]
> Delphi Berlin

on Delphi Berlin this error is present also in VERSION 3_1_0_lithium BUILD DATETIME 2019-01-08T15:05:57.955330

**Comment by danieleteti** [comment]
Please, some of you with a version <= Berlin, could change this unit? Check the class helper `TMVCActiveRecordHelper` defined just after the `TMVCActiveRecord` class.
[MVCFramework.ActiveRecord.pas.zip](https://github.com/danieleteti/delphimvcframework/files/2982939/MVCFramework.ActiveRecord.pas.zip)

**Comment by krivoj** [comment]
Partial Fix with ClassHelper. See attachments.
[MVCFramework.ActiveRecord.zip](https://github.com/danieleteti/delphimvcframework/files/2984961/MVCFramework.ActiveRecord.zip)



**TMVCActiveRecord.MapTValueToParam**
...
    ftGuid:
      begin
        aRTTIField.SetValue(Self, TValue.From<TGUID>(aField.AsGuid));
      end;
...
ERROR: [dcc32 Error] MVCFramework.ActiveRecord.pas(1124): E2003 Undeclared identifier: 'AsGuid'

...
        if not aValue.IsInstanceOf(TStream) then
          raise EMVCActiveRecord.CreateFmt('Unsupported reference type for param %s: %s',
            [aParam.Name, aValue.AsObject.ClassName]);
        lStream := aValue.AsType<TStream>(false);
        if Assigned(lStream) then
...
ERROR: [dcc32 Error] MVCFramework.ActiveRecord.pas(1212): E2034 Too many actual parameters

**TMVCActiveRecord.SelectRQL**
...
  try
    Result := lAR.SelectRQL(RQL, MaxRecordCount);
  finally
    lAR.Free;
...
ERROR: [dcc32 Error] MVCFramework.ActiveRecord.pas(1563): E2531 Method 'SelectRQL' requires explicit type argument(s)

**Comment by oakrom** [comment]
*class function TMVCActiveRecord.Count(const aClass:
TMVCActiveRecordClass): int64;*

…

  try

    Result := lAR.Count;  *(COMPILER SHOWS HERE)*

  finally

    lAR.Free;

  end;



ERROR: [dcc32 Error] MVCFramework.ActiveRecord.pas(979): E2531 Method
'Count' requires explicit type argument(s)



*procedure TMVCActiveRecord.MapColumnToTValue*

…

ftGuid:

      begin

        aRTTIField.SetValue(Self, TValue.From<TGUID>(aField.AsGuid));
*(COMPILER
SHOWS HERE)*

      end;

…



ERROR: [dcc32 Error] MVCFramework.ActiveRecord.pas(1138): E2003 Undeclared
identifier: 'AsGuid'



*procedure TMVCActiveRecord.MapTValueToParam*

…

tkClass:

      begin

        if not aValue.IsInstanceOf(TStream) then

          raise EMVCActiveRecord.CreateFmt('Unsupported reference type for
param %s: %s',

            [aParam.Name, aValue.AsObject.ClassName]);

        lStream := aValue.AsType<TStream>(false); *(COMPILER SHOWS HERE)*

        if Assigned(lStream) then

…



ERROR: [dcc32 Error] MVCFramework.ActiveRecord.pas(1226): E2034 Too many
actual parameters





*class function TMVCActiveRecord.SelectRQL*

…

try

    Result := lAR.SelectRQL(RQL, MaxRecordCount); *(COMPILER SHOWS HERE)*

  finally

    lAR.Free;

  end;

…



ERROR: [dcc32 Error] MVCFramework.ActiveRecord.pas(1577): E2531 Method
'SelectRQL' requires explicit type argument(s)

вт, 19 мар. 2019 г. в 23:33, Gabriele Canazza <notifications@github.com>:

**Comment by danieleteti** [comment]
Here's the updated version. 
- The problem with `SelectRQL` is fixed (workaround for a compiler bug).
- The problem about `AsGUID` must be fixed by someone of you using an older version of Delphi. What I can do is to IFDEF that part, but I'd like to mantain the same level of features for every Delphi version.
[MVCFramework.ActiveRecord.pas.zip](https://github.com/danieleteti/delphimvcframework/files/3037415/MVCFramework.ActiveRecord.pas.zip)

Please, let me know

**Comment by davuteryilmaz** [comment]
All fixes to compile the framework in Seattle.

- The problem about `AsGUID `is fixed in **MVCFramework.ActiveRecord.pas**.
- The problem about `TValue.AsType<T>` is fixed in **MVCFramework.ActiveRecord.pas**.
- The problem about `TStrings.AddPair` is fixed in **MVCFramework.ActiveRecordController.pas**.
- The problem about `TZDecompressionStream.Create `is fixed in **MVCFramework.RESTClient.pas**.
[MVCFramework Seattle Fixes.zip](https://github.com/danieleteti/delphimvcframework/files/3042991/MVCFramework.Seattle.Fixes.zip)

**Comment by krivoj** [comment]
it's all Ok but i have EurekaLog ( disabled in this project ) and there is this error:
![dmc-eurekalog-Error](https://user-images.githubusercontent.com/21248199/55571150-39578200-5705-11e9-9c40-995e0a15fd99.png)

**Comment by krivoj** [comment]
without eurekalog is all OK on Seattle and Berlin.
