### ISSUE TITLE
BLOB Field in Activerecord

### ISSUE THREAD

**Issue by budisatya** [danieleteti/delphimvcframework#315]
i used firebird 2.5.9 and DMVC Boron,
i create blob field in firebird ex:
 create tableX (
  id integer not null,
  notes blob sub_type text
);
in active record entity class i use
Notes : String
whene i call rest from client, if blob field is empty, there no error, if blob field has any value, it generate error
 "Exception Class Name : EEncodingError
Exception Message : No mapping for the Unicode character exists in the target multi-byte code page"
How to fix this problem? 
or any oher idea to contain/load blob field in active record?

**Comment by danieleteti** [comment]
What is the blob encoding?

**Comment by budisatya** [comment]
blob encoding use default / none

**Comment by budisatya** [comment]
![fdb](https://user-images.githubusercontent.com/16058350/71330424-94652980-255f-11ea-99e1-46a8c06a3f21.jpg)
setting in delphi FDConnection

**Comment by danieleteti** [comment]
I cannot reproduce the issue - in all the samples the blob textual field is correctly handled. I've updated the sample `samples\activerecord_showcase` just to show you the correct way to do it. 
IMHO the problem is in your characterset. As a general advice, is way better to be explicit about the character set used by the database and the tables fields.

**Comment by budisatya** [comment]
oke, i'll check samples
