### ISSUE TITLE
Nullable problem with Floating points

### ISSUE THREAD

**Issue by ads69** [danieleteti/delphimvcframework#344]
Hi, I face 2 problems with the Nullable types 
When using the activerecord_showcase sample :
 - in the Nullable Test, if I do 
```
    lTest.f_float8 := 56.5;
    lTest.Insert;
```
I get an error saying that '56.5' is not a corect floating point value (French OS, SQlite)
- if I replace the property F_Float8 from NullableDouble to NulableExtended I get a "unsupported Record TypeKind (14) for param F_Float8" error when the application start.

Best regards

Armindo

**Comment by danieleteti** [comment]
I cannot reproduce the behaviour. Changing the value to 56.5 the sample still works as expected. Can you provide a selfcontained sample?

**Comment by ads69** [comment]
Do you mean a compiled exe with sources ?

**Comment by ads69** [comment]
[activerecord_showcase.zip](https://github.com/danieleteti/delphimvcframework/files/4344431/activerecord_showcase.zip)

here the source + exe. I think it is a decimal separator issue. My regional settings in based on French settings

**Comment by danieleteti** [comment]
The problem was related to the sqlite type affinity. The table is created by a postgresql schema definition. SQLite doesn't raise esserrs in case of wrong type name, they are just a "type hint". So the float8 type was recognized as TEXT and the convertion while reading the data raises an exception. I've just updated the database related to the sample and all works now. In the unit test the table is created directly by the code so the problem doesn't raise. Pull the last version of `dmvcframework\samples\data\activerecorddb.db` and all works. No code changed are needed.

**Comment by ads69** [comment]
Daniele,
is the NulableExtended property fixed also ?
best regards

**Comment by danieleteti** [comment]
No problems are raised with the new database structure. So I think that it should be fixed as well. Let me know if you find any problems.

**Comment by ads69** [comment]
Ok Daniele, will do some tests today and let you know.

**Comment by ads69** [comment]
Daniele, it is fixed.
Thanks again.
