### ISSUE TITLE
(Nullable) Attribute for not serializing property or a field if it is Null

### ISSUE THREAD

**Issue by ads69** [danieleteti/delphimvcframework#451]
Hi,
 When working with Nullable types it would be nice to have a new attribute to serialize only non null fields (or properties), empty arrays, null sub objects. 
In this case  the resulting json could be significantly reduced in size and reduce network bandwidth.
Best regards

Armindo

**Comment by danieleteti** [comment]
Yes, we considered this. However this would introduce an incongruency between serialization and deserialization. While deserializing a nullable field, in case of `null` that value is setted on the deserialized object (previous value is overwritten), while in case of empty property the value will remain the same.  This is the reason because also null fields are serialized.
