### ISSUE TITLE
Adding support for Rate Limiting

### ISSUE THREAD

**Issue by ads69** [danieleteti/delphimvcframework#505]
Hi,
to avoid too many requests and DOS attacks to the API server it would be nice to have a API Rate Limiting.
I mean for instance if a user exceeds the API Call limits for a short period, it raizes a [HTTP 429](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429) response.
Nice topics about it [here](https://nordicapis.com/everything-you-need-to-know-about-api-rate-limiting/).
Best regards

Armindo

**Comment by fastbike** [comment]
You need to define what you are trying to achieve here:
- 1. prevention of DOS / DDOS attacks
- 2. rationing of scarce server resources to genuine users
- 3. rate limiting according to the level of service a customer has subscribed to

In many cases you are better off handling this with an API manager, rather than in the application server.
For #1, you need external protection - by the time the request hits the app server you have lost the battle.
For #2, decide on how much service you can afford to deploy and write your app to allow the type of scaling you can get with  AWS, Azure etc, where additional instances can be stood up to handle peak demand.
For #3, you can use an API manager, or you could write your own  middleware class that implements a subscription limited rate.

**Comment by ads69** [comment]
I'm trying to achieve case 3. I have a customer that send too much reuest to the API server.
I would like to limit the number of request per minutes (for instance 50 request per minutes).
I agree a middleware would be the best choice for this.
Maybe storing the number of request in the session and checking if the limit is not reached. and each minutes reseting the counter.
Will try to explore this way.

**Comment by danieleteti** [comment]
@ads69 as @fastbike said the rate-limiting stuff is normally an "infrastructure" concern because when the application server need to understand if can or cannot serve a specific request you already fail to protect your precious service resources. However, from time to time happens that some users ask for a quick-and-dirty solution for small/mid services which have to protect themselves from occasional spike of requests. In this case a middleware can be a good solution. I was thinking for a small and light solution. The 3rd case to which @fastbike was referring to, is a bit difficult to implement in case of cluster servers (they have to communicate about the request/timeframe the customer already did, however it's implementable easily if you have a common key-value storage (redis?). We did this a number of time using redis. In a single server architecture is quite simple.

**Comment by ads69** [comment]
@danieleteti you are both right.
I will try to make a middleware for a little different purpose.
Some of my customers install the API server in their company, but won't install tools like redis to avoid having limitation.
In this case a middleware that restrict them to use the API internally in a dirty and wrong way, will force them to use the API safely. The only problem I face is the lot of support because some customers use the API in a wrong way.
For instance I have a customer that makes 6 to 7 request per second where for this purpose 10 to 20 request per day is enought.
When this Middleware will be done, will make it available here.

**Comment by danieleteti** [comment]
@ads69 yes, I got the point. The ratio is: "if the rate limit check cost less than the request itself, then do the check" :-)
Let us know about the progress.

**Comment by ads69** [comment]
Hi,
I wanted to store the Request count directly in the Logged User customData in the OnBeforeControllerAction event of the MiddleWare like this : 
`Context.LoggedUser.CustomData.AddOrSetValue('RequestCount', RequestCount.ToString);`
But it is not saved (maybe overwritten by the JWT Token).
Where could I store these user informations ?
Best regards

**Comment by joaoduarte19** [comment]
> Hi,
> I wanted to store the Request count directly in the Logged User customData in the OnBeforeControllerAction event of the MiddleWare like this :
> `Context.LoggedUser.CustomData.AddOrSetValue('RequestCount', RequestCount.ToString);`
> But it is not saved (maybe overwritten by the JWT Token).
> Where could I store these user informations ?
> Best regards

I think the best way for you to store data is to create a global class (singleton) to store this data.
