### ISSUE TITLE
Code patterns in dispatch of middleware

### ISSUE THREAD

**Issue by HealthOneNZ** [danieleteti/delphimvcframework#597]
I'm curious as to why the code patterns in these TMVCEngine methods are different:
`    ExecuteBeforeRoutingMiddleware`
`    ExecuteBeforeControllerActionMiddleware`
`    ExecuteAfterControllerActionMiddleware`
`    ExecuteAfterRoutingMiddleware`

The first two methods use a type enumerator (for var in collection) to iterate over the list of middleware. My understanding is that the order will depend on how the default enumerator has been implemented and there is no guarantee it will execute in any given order.

The other two methods use a traditional for loop (for var = 0 to count etc) to index into the collection of middleware. Thus the order of execution corresponds to the order the middleware were registered into the engine.

**Comment by danieleteti** [comment]
The default enumerator implementation used by the TList<T> is the type `TEnumerator = class(TEnumerator<T>)` declared in `System.Generics.Collections` iterates the element from the index `0` to `Items.Count - 1` so it provides items in the same orders. However, I got your point. The loop are written in a different way just because have been written in different "Delphi ages".
