### ISSUE TITLE
How to improve this situation

### ISSUE THREAD

**Issue by pppp0836** [danieleteti/delphimvcframework#656]
Hi All, My dmvc application has run for half a day in  Windows Server 2012, The threads count and memory usage just made me crazy,
So I would like to ask you all how to solve this problem，Thanks anyway.

Here is CPU&Memory Usage:
![dmvc](https://github.com/danieleteti/delphimvcframework/assets/50391717/b995c995-3e78-420b-9a73-9ddfdb486c12)
Here is Application Code snippets:
![dmvc1](https://github.com/danieleteti/delphimvcframework/assets/50391717/ad16d18f-2541-4240-9dd6-65ddd73ad5ae)

**Comment by Microcom-Bjarne** [comment]
Without more information - sourcecode or better explanation of your application. I think it will be difficult to answer your question. I can however compare with 10 applications built with dmvc 3.2.2 I've been running for weeks / months .. and none of them is currently using more than 10 threads or 5mb memory.

So I think it will come down to - what your application is doing?
But one line of code you have supplied tells me that you are "building" something, that could cause the memory usage.

`BuildContainer;`

Sound to me like you are holding some information in memory. But how much?

**Comment by joaoduarte19** [comment]
Your app is probably experiencing a memory leak. Try to monitor this application with some memory leak capture tool, like FastMM or EurekaLog, to find out where these memory leaks are.

I can assure you that the problem is not in the DMVC structure, as I have application servers running for months with low memory consumption and very little processing.

**Comment by danieleteti** [comment]
As other guys told, we have too few information to really help. Please provide more code and context.

**Comment by fastbike** [comment]
As a first step, given you are running using the TIdHttpWebBroker console based runner, I would run the app in debug mode. In the IDE, open the system.pas file and put a breakpoint on the last line, the one that is "end."

Let your app handle a few requests and then close down from the console - Ctrl C from line 66 of your code.
When the debugger stops at the breakpoint switch back to the console and see if any memory leaks are reported.

We have a large app running under IIS, that has been in production for 4 years. While it sometimes uses a large chunk of memory and plenty of CPU, that is because it is caching a lot of info and serving millions of requests per day. The only time we have had issues with instability is in the code written in our application, not in the underlying framework.

Good luck tracking this down - it can be baffling at the start.

BTW, we use Eurekalog. If you are running a commercial application you really should be logging call stacks etc to help in debugging.
